### ISSUE TITLE
Editing the font family preferences often does nothing in 1.81 (1.81.0)

### ISSUE THREAD

**Issue by bryanrieger** [TobyLobster/Inform#14]
When changing the font in Preferences > Editing > Font family to something like 'Menlo' (or other fonts available by default with macOS) no visible change is reflected despite the font name being reflected in the preference.

I can only currently change it to Monaco, Geneva, Georgia, Helvetica, Impact, Lucida Grande (default), Tahoma, and Verdana. All other fonts will display as Lucida Grande, even though their font family name is reflected in the preference.

**Comment by TobyLobster** [comment]
Thank you for the report. The problem should be fixed in the upcoming release.
