### ISSUE TITLE
Documentation font size jumps are too large.

### ISSUE THREAD

**Issue by bryanrieger** [TobyLobster/Inform#15]
Currently when trying to adjust the documentation font size (also the font size used while running the project) it's impossible to set a moderate, readable size. It's either too small, or too big. The first four 'stops' on the slider are all quite tiny, while the stops on the right side feel more inline with expectations. The middle stop font size still feels small, while the next stop up feels larger than comfortable.

One solution would be to increase the size of the smallest font and reduce the distance between steps. This should allow for a few other interim moderate sizes.

Another solution would be to provide a font select field/button (like Font family above) where the user can choose the font and font size used in the documentation and runtime using the default macOS font dialog.

--

I could also see where having a separate font and size preference for both the documentation and the runtime would be desirable, but would then require 3 font family selection options; editor font family/size, documentation font family/size, runtime font family/size.

**Comment by TobyLobster** [comment]
The gradations were too far apart and not evenly spaced. Hopefully this will be sufficient. This is now fixed, and will appear in the upcoming release.
