### ISSUE TITLE
"Replay" button is replaying actions in reverse

### ISSUE THREAD

**Issue by poeticbulldozer** [TobyLobster/Inform#16]
When I hit the replay button, my actions are replayed in the order reverse to how I originally did them. For example, taking the actions >get up ; >look; >go north ; then replaying, will result in the replay trying >go north ; >look ; >get up. If I replay it a second time, the actions will invert again, once more conforming to the original order!

**Comment by TobyLobster** [comment]
Thank you for the report. This will be fixed in the upcoming release.
