### ISSUE TITLE
Status field is vertically misaligned

### ISSUE THREAD

**Issue by angstsmurf** [TobyLobster/Inform#17]
The status field does not align vertically with the search bars on its sides, but is slightly higher. I've only tested this on 12.5 Monterey.

<img width="618" alt="statusbar" src="https://user-images.githubusercontent.com/5066755/183248738-1cfef184-8188-4aa5-a102-21c1dea69dbb.png">

**Comment by TobyLobster** [comment]
Should be aligned now on Monterey.

**Comment by angstsmurf** [comment]
I can confirm that it looks fine here on 12.5.

**Comment by TobyLobster** [comment]
Thanks.
