### ISSUE TITLE
Won't compile on Apple Silicon due to "Build Active Architecture Only" settings

### ISSUE THREAD

**Issue by angstsmurf** [TobyLobster/Inform#19]
I see that build instructions are at the top of the pipeline, but I in case anyone else has similar problems, I thought I'd share my findings.

Many of the subprojects have different build settings, and the main stumbling block seems to be "Build Active Architecture Only", which is set to NO for the main Inform project but YES for debug builds in most (all?) of the subprojects, which caused build errors because Xcode couldn't find the X86-64 binaries it was looking for.

Here's how I got it to build  using Xcode 13.4.1 on an M1 Macbook Air with Monterey:
• Clone the project and get the submodules with `git pull --recurse-submodules`. I first tried to update an existing clone of an older version, but that wouldn't work.
• Change the Team setting on the Inform target to your own team or turn off signing ("Sign to Run Locally".)
• Set all projects to "Build Active Architecture Only" for debug builds.

**Comment by TobyLobster** [comment]
This should be resolved now. Everything is set to NO for "Build Active Architecture Only", and all submodules should build correctly (*crosses fingers*).
