### ISSUE TITLE
Interpreter falsely claims to support line input echo suppression

### ISSUE THREAD

**Issue by angstsmurf** [TobyLobster/Inform#23]
When running Counterfeit Monkey in the internal Zoom interpreter, all typed input commands are now repeated after pressing Enter, that is, the command line is re-printed on the line below the entered command.

The game checks whether the interpreter supports  line input echo suppression, and Zoom now claims that it does. The old version didn't. But the actual suppression doesn't seem to be working, causing the input to be echoed twice.

**Comment by TobyLobster** [comment]
@MaddTheSane Do you have any thoughts about this issue?

**Comment by MaddTheSane** [comment]
I'll look into it.

**Comment by MaddTheSane** [comment]
Should be fixed in https://github.com/MaddTheSane/CocoaGlk/commit/d64c99e601d83b9b3daa78e704013ae2ad877027

**Comment by angstsmurf** [comment]
I can confirm that this fixes the problem. Good work!

**Comment by TobyLobster** [comment]
Thanks @MaddTheSane , pushed.
