### ISSUE TITLE
IFTF logo isn't transparent

### ISSUE THREAD

**Issue by angstsmurf** [TobyLobster/Inform#24]
The IFTF logo shown on the launcher has a solid white background, which doesn't look great. It would be nicer if it was transparent. Perhaps a vector graphic could be used with a custom fill colour that gets lighter in dark mode.

<img width="155" alt="iftf" src="https://user-images.githubusercontent.com/5066755/183839568-e7d8117c-514d-4fb0-bf3c-462421288651.png">

**Comment by TobyLobster** [comment]
The logo doesn't look very good with a transparent background, so instead I've added a thin black border around it.
