### ISSUE TITLE
Links in Report view not working after compiling legacy version

### ISSUE THREAD

**Issue by angstsmurf** [TobyLobster/Inform#25]
After doing a release, Inform will show a file hierarchy in the Results > Report view. Clicking on the file and folder icons here used to open their equivalents in Finder, but now they all seem to lead to the Documentation view instead.
<img width="305" alt="Skärmavbild 2022-08-10 kl  10 27 10" src="https://user-images.githubusercontent.com/5066755/183853834-06c2c124-898c-48dc-9c04-fed4864509f0.png">

EDIT: I just noticed that this only happens when the project is set to a legacy language version (such as 6M62), so I updated the title. When compiling to Inform 10.1.0 or Current, the links work as intended.

The console will show errors such as:
```
IFDocumentationPage: failed to load URL file:///Users/XXXX/Desktop/Untitled.inform/Build/%5BJAVASCRIPTPRELUDE%5DopenFile(%22/Users/XXXX/Desktop/Untitled.materials/Release%22) with error: The requested URL was not found on this server.
```

**Comment by TobyLobster** [comment]
I can't replicate this with latest version.

**Comment by angstsmurf** [comment]
Seems to work fine here as well. Thanks!
