### ISSUE TITLE
 Inform7 IDE Slow Editing

### ISSUE THREAD

**Issue by wmodes** [TobyLobster/Inform#28]
I originally reported this issue back in Jan 2021 with Inform7 v1.68.1. I downloaded the most recent build of v10.1.2 and was surprised to see it was still an issue (original report [here](https://intfiction.org/t/inform7-ide-slow-editing/49086))

I’m editing a larger file in the Inform7 IDE and am experiencing very slow editing. I’ve searched and found no one else reporting this. I can edit small files with no lag, but large files present a huge lag as I type. Compiling happens at normal speed. Attached is a link to a video of me typing far ahead of the buffer.

[Screen Recording Slow Inform7 IDE](https://drive.google.com/file/d/16f-CIs83oZXCaPEF7i_fSLG61G4e0U_M/view?usp=sharing)

Here are the deets of my file:

The 33597-word source text has successfully been translated into a world with 41 rooms and 184 things, and the index has been brought up to date.

And the details of my version of Inform:

Download file: inform_10_1_2_macOS_1_82_3.dmg
Inform version: 1.82 (1.82.3)
OS: MacOS Montereey v12.6 (21G115)

But this also happens with earlier versions of Inform, such as I7-6M62-OSX.dmg. In the earlier investigation, there was some suspicion that it might be related to the touch bar handling.

Unfortunately, this makes the IDE unusable. 

Thanks for any leads to fixing this.

**Comment by TobyLobster** [comment]
I don't have a fix for this issue yet, but you might like to know about a possible workaround in v10.1.2:

1. In Preferences->Editing, turn off 'Enable Styles'
2. In Preferences->Colour, turn off 'Enable Colouring'

Obviously this turns off all the syntax highlighting so this is not a great solution. But I hope the text editing speed should be more acceptable.

**Comment by angstsmurf** [comment]
Also, if you build the Inform IDE from the source yourself, this hack (disabling the touch bar) still works:
https://intfiction.org/t/inform7-ide-slow-editing/49086/24

**Comment by wmodes** [comment]
I wondered if that hack still works. I've never built Inform from source and found [Tony's instructions](https://github.com/TobyLobster/Inform/blob/master/documentation/building_inform.md). Unfortunately, it skips over the entire code build which I've never done. Anyone have any pointers to completing that build?

**Comment by wmodes** [comment]
Well, I figured it out, but that didn't go well.

'interp_z3.h' file not found in interp.c:

```
#ifdef HAVE_COMPUTED_GOTOS
# define TABLES_ONLY
# include "interp_z3.h"
# include "interp_z4.h"
# include "interp_z5.h"
# include "interp_z6.h"
# undef TABLES_ONLY
```

**Comment by TobyLobster** [comment]
If you are willing to experiment a little:

Try unzipping the enclosed file in the 'zoom/build' directory (make the 'build' directory if you don't have it) and try building the Inform App in Xcode again.

[zoom_build.zip](https://github.com/TobyLobster/Inform/files/9648234/zoom_build.zip)

**Comment by wmodes** [comment]
Well, I was willing to experiment. Thanks @TobyLobster for the pre-build zoom files. I tried variations on signing the source as Mac Developer, Apple Developer, and Sign to Run Locally because I didn't have an Apple Developer ID. All happily build (via Archive) successfully. However, the Inform.app seemed to quietly crash. 

I tried going into Inform.app/Contents/MacOS and running Inform directly. I got:
```
MacOS % ./Inform
dyld[30694]: Library not loaded: '@rpath/GlkSound.framework/Versions/A/GlkSound'
  Referenced from: '/Applications/Inform.app/Contents/MacOS/Inform'
  Reason: tried: '/usr/lib/swift/GlkSound.framework/Versions/A/GlkSound' (no such file), '/Applications/Inform.app/Contents/MacOS/../Frameworks/GlkSound.framework/Versions/A/GlkSound' (code signature in <D3B99BC3-7415-383A-9666-C3FA969A61DF> '/Applications/Inform.app/Contents/Frameworks/GlkSound.framework/Versions/A/GlkSound' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/swift/GlkSound.framework/Versions/A/GlkSound' (no such file), '/Applications/Inform.app/Contents/MacOS/../Frameworks/GlkSound.framework/Versions/A/GlkSound' (code signature in <D3B99BC3-7415-383A-9666-C3FA969A61DF> '/Applications/Inform.app/Contents/Frameworks/GlkSound.framework/Versions/A/GlkSound' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/System/Library/Frameworks/GlkSound.framework/Versions/A/GlkSound' (no such file)
[1]    30694 abort      ./Inform
```
Looks like GlkSound didn't build?

Sad face. This is new territory, so apologies for what are probably noob errors.

**Comment by TobyLobster** [comment]
It's a signing issue. From the output you quote: "GlkSound' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)". Sorry, I think you need an Apple Developer ID.

When I have time, I'll have to try the hack suggested above. If it works I'll get a new version out.

**Comment by wmodes** [comment]
Any thoughts, @tonyLobster?

**Comment by wmodes** [comment]
Bump.

**Comment by wmodes** [comment]
@TonyLobster, it seemed your `--local` param in config.py didn't do anything.

I thought it would be useful to have a `--local` param that set `CODE_SIGN_IDENTITY` to `-` which is apparently xcode's designation for "Sign to Run Locally"

When I configured the build with Sign to Run Locally and with my Developer Team ID (retrieved from my keychain), I no longer had the signing issue. However, I had another problem (below). Here's the modified `configure.py`

[configure.py.zip](https://github.com/TobyLobster/Inform/files/9760574/configure.py.zip)

**Comment by wmodes** [comment]
Okay, when I ran the `inform.app` here's what I got (partial):

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@rpath/GlkSound.framework/Versions/A/GlkSound'
Referenced from: '/Applications/Inform.app/Contents/MacOS/Inform'
Reason: tried: '' (no such file), '' (code signature in <D3B99BC3-7415-383A-9666-C3FA969A61DF> '' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '' (no such file), '' (code signature in <D3B99BC3-7415-383A-9666-C3FA969A61DF> '' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adh
(terminated at launch; ignore backtrace)
```

So interestingly, GlkSound still had a signing issue.

**Comment by wmodes** [comment]
Interestingly, when i sign with my Developer Team ID using the `--develop` flag, the build fails at the last step trying to sign the `inform.app` with the following:

```
CodeSign /Users/wmodes/Library/Developer/Xcode/DerivedData/Inform-gzkwiqfmupwuzfcumalzutqxrtdm/Build/Intermediates.noindex/ArchiveIntermediates/Inform/InstallationBuildProductsLocation/Applications/Inform.app (in target 'Inform' from project 'Inform')
    cd /Users/wmodes/dev/inform-build/Inform/inform
    
    Signing Identity:     "Apple Development: wmodes@gmail.com (WXH9UQURVG)"
    
    /usr/bin/codesign --force --sign D8C39DC04CC612A0B96F106603CA717C5D93F01C -o runtime --entitlements /Users/wmodes/Library/Developer/Xcode/DerivedData/Inform-gzkwiqfmupwuzfcumalzutqxrtdm/Build/Intermediates.noindex/ArchiveIntermediates/Inform/IntermediateBuildFilesPath/Inform.build/Release/Inform.build/Inform.app.xcent --generate-entitlement-der /Users/wmodes/Library/Developer/Xcode/DerivedData/Inform-gzkwiqfmupwuzfcumalzutqxrtdm/Build/Intermediates.noindex/ArchiveIntermediates/Inform/InstallationBuildProductsLocation/Applications/Inform.app

/Users/wmodes/Library/Developer/Xcode/DerivedData/Inform-gzkwiqfmupwuzfcumalzutqxrtdm/Build/Intermediates.noindex/ArchiveIntermediates/Inform/InstallationBuildProductsLocation/Applications/Inform.app: code object is not signed at all
In subcomponent: /Users/wmodes/Library/Developer/Xcode/DerivedData/Inform-gzkwiqfmupwuzfcumalzutqxrtdm/Build/Intermediates.noindex/ArchiveIntermediates/Inform/InstallationBuildProductsLocation/Applications/Inform.app/Contents/MacOS/6M62/ni
Command CodeSign failed with a nonzero exit code
```

Experimenting on the command line, I get the same error with the `codesign`  command, but the `--deep` command line option works. But it feels a little hacky.

**Comment by wmodes** [comment]
Further experimentation...

Once I signed the inform.app with the `--deep` command line option, I could actually run Inform for the first time from a build. Copying it from this obscure xcode location (`/Users/wmodes/Library/Developer/Xcode/DerivedData/Inform-gzkwiqfmupwuzfcumalzutqxrtdm/Build/Intermediates.noindex/ArchiveIntermediates/Inform/InstallationBuildProductsLocation/Applications/Inform.app`) to my apps directory, I was good to go. 

So this indicates a couple things:

* The build doesn't seem to work with the `--local` config options, i.e., "Sign to Run Locally"
* The build DOES seem to work with the `--develop` config option with the Developer Team ID. But...
* The final signing fails because there is some package in there that doesn't inherit the signing team from the xcode project

I haven't tested yet whether this solves the original problem of the slow text using the zoom header files you passed me.

Testing....

Turns out, nope.

Oh wait, I haven't done this little tidbit from [Petter Sjölund](https://intfiction.org/u/Angstsmurf) yet:

> If you add the lines
> ```
> - (NSTouchBar *)makeTouchBar {
>   return nil;
> }
> ```
> somewhere in IFSourceFileView.m and build Inform from source, the problem goes away.

Now when I rebuild...

IT WORKS. Daaaanm, thanks. This is the first time I've been able to work on my project in months.

**Comment by TobyLobster** [comment]
I'm so glad you got up and running, that's good to hear! I'll put out a new version when I get a moment. Busy on other things right now, but soon (crosses fingers).

**Comment by wmodes** [comment]
I would be glad to see this as part of the release.

**Comment by TobyLobster** [comment]
This should be fixed now.
