### ISSUE TITLE
Issues w/launching from outside IDE on MacOS

### ISSUE THREAD

**Issue by wmodes** [TobyLobster/Inform#30]
I have been using VS Code with the Inform 7 extension. I can edit in VS Code and just launch the compiler from the editor, which compiles and launches my external player Lectrote. I've only gotten it to work linked to the `6M62` versions of `ni` and `cBlorb`.

I have not yet managed to compile successfully with Inform7 10.1. 

After my somewhat custom build with the help of Toby, here are the versions I'm running:
```
% ./cBlorb --version
inblorb version 4 'Duralumin' (20 August 2022)
% ./ni --version
inform7 version 10.1.0 'Krypton' (20 August 2022)
% ./inform6 -h
Inform 6.41 for MacOS (22nd July 2022)
```
When I try to compile I get the following error:

> /Applications/Inform.app/Contents/MacOS/ni --internal /Applications/Inform.app/Contents/Resources/retrospective/6M62 --external /Users/wmodes/Library/Inform --project /Users/wmodes/dev/bearcreek/Experiments/test2.inform --format=ulx
> (-format=ulx is deprecated: try -format=Inform6/32d instead)
> Inform 7 v10.1.0 has started.
>   &gt;--> An internal error has occurred: Unable to open model CSS material for reading. The error was detected at line 332 of "/Users/tobynelson/Code/Inform Core/inweb/foundation-module/Chapter 5/HTML.w". This should never happen, and I am now halting in abject failure. What has happened here is that one of the checks Inform carries out internally, to see if it is working properly, has failed. There must be a bug in this copy of Inform. It may be worth checking whether you have the current, up-to-date version. If so, please report this problem via www.inform7.com/bugs. As for fixing your source text to avoid this bug, the last thing you changed is probably the cause, if there is a simple cause. Your source text might in fact be wrong, and the problem might be occurring because Inform has failed to find a good way to say so. But even if your source text looks correct, there are probably rephrasings which would achieve the same effect. (Error in /Users/wmodes/dev/bearcreek/Experiments/test2.inform/Source/story.ni, line 1)

Obv, it'd be nice to use Inform 10.1 so I can take advantage of the updated extensions in the "friends" library.

**Comment by TobyLobster** [comment]
Is this still an issue for you? 

From the output it looks like you are calling the latest version of ni (Contents/MacOS/ni) but with --internal set to a retrospective folder (Contents/Resources/retrospective/6M62). They should match. If you look at the Console section within the Results tab in the IDE you should be able to see the full command line being used and so tweak your workflow accordingly.

**Comment by berkeleynerd** [comment]
I am not the original poster but I can confirm that this answer lead me to a working solution.

**Comment by TobyLobster** [comment]
Thank you for confirming, that's good to know.
