### ISSUE TITLE
Contents View Displays White Text on Light Background (Text Unreadable)

### ISSUE THREAD

**Issue by danyadsmith** [TobyLobster/Inform#32]
The contents view in **Version 1.82.3** displays white text on a light background, making the text unreadable. This does not appear to be linked to the customizations I've made to the dark or light themes. The issue persists when I select a theme from the default settings.

Here are a few screenshots that demonstrate the issue:

**Using a Light Theme**

![2022-12-17_10-15-01_CustomLightTheme_SourceView](https://user-images.githubusercontent.com/1380547/208249067-ea0b5e3f-5f53-454e-89e8-35c370fd33ee.gif)
![2022-12-17_10-15-13_CustomLightTheme_ContentsView](https://user-images.githubusercontent.com/1380547/208249072-56205c54-f744-436a-9073-937016a117cd.gif)

**Using a Dark Theme**

![2022-12-17_10-16-28_CustomDarkTheme_SourceView](https://user-images.githubusercontent.com/1380547/208249077-5db504f9-e88d-4714-89f2-f7db3ccb0e31.gif)
![2022-12-17_10-17-31_CustomDarkTheme_ContentsView](https://user-images.githubusercontent.com/1380547/208249081-40f9c418-d871-4ed5-8cde-4fe13eda1284.gif)

p.s. I love what you've done with the Inform7 UI, especially the addition of Light and Dark Mode color schemes!

**Comment by danyadsmith** [comment]
An update: 

This behavior is tied to the macOS Dark Mode setting. In Light Mode, the contents list appears in black text as expected.

**Comment by TobyLobster** [comment]
Thanks, now fixed.

**Comment by beerandjesus** [comment]
Hi, any idea when this will be released? It's pretty annoying for those of us who are used to dark mode on Mac. Latest Mac build for the IDE I can find is from 11 months ago...
