### ISSUE TITLE
Inform 6 inclusions unreadable in dark mode

### ISSUE THREAD

**Issue by angstsmurf** [TobyLobster/Inform#40]
It wouldn't surprise me if this is a known issue. See the attached image:

<img width="457" alt="Skärmavbild 2023-04-20 kl  11 21 13" src="https://user-images.githubusercontent.com/5066755/233322150-c03286de-9f69-44ab-a20a-07f048536f11.png">

**Comment by TobyLobster** [comment]
Thanks - should be fixed now.
