### ISSUE TITLE
Skein file causes the IDE to hang on load

### ISSUE THREAD

**Issue by xtreme-james-cooper** [TobyLobster/Inform#6]
Sorry if this isn't the correct place - Mantis is down, and I was directed here.

The following Skein file was generated by the IDE, but hung when I tried to test it:
[badskein.txt](https://github.com/TobyLobster/Inform/files/5220126/badskein.txt)
After that, I couldn't reopen the project at all until I deleted the skein file wholesale and let the IDE regenerate a blank one. You can reproduce by starting a new project, pasting the contents into its skein file, then trying to open the project.

I think the error is around node 1104ish, because that's the action I changed that broke everything, but couldn't swear to it.

I am on the new IDE version, Version 1.68 (1.68.1), and a Mac running Catalina 10.15.6 (19G2021).

**Comment by TobyLobster** [comment]
Sorry this fix is two years too late, but better late than never I guess. This will be fixed in the next release.
