### ISSUE TITLE
Missing cursor?

### ISSUE THREAD

**Issue by geoffdgeorge** [TobyLobster/Inform#7]
At the moment, no blinking text cursor is visible when editing the Source document in MacOS Catalina, making it difficult to know where I'm about to type at any given moment. 

Been editing my Source document in VSCode instead and copying and pasting back into the IDE for testing, but this quickly starts to become a pain.

Possible to add a cursor in the near future?

**Comment by geoffdgeorge** [comment]
Update: I see that the cursor works, but in Light Mode only, not Dark Mode.

**Comment by TobyLobster** [comment]
Fixed.
